### ISSUE TITLE
Weird behavior when switching between prod and dev mode in tolgee and providing credentials

### ISSUE THREAD

**Issue by morrisjdev** [tolgee/chrome-plugin#8]
Hey,

first of all I want to say great job. This tool looks pretty promising and I'm currently setting it up in a larger code base (Angular project). I am really hyped and think this could be the next big thing when developing localized apps.

I discovered a minor issue when working with the extension and trying to override the API credentials used in a testing environment. My plan of usage is somewhat against whats documented in the section "In context translation" in the documentation but I think it might be an interesting use case.

My situation is the following:
The app runs in a multi stage environment (in addition to the local developers environment) with the three stages dev, testing and prod. In prod the translations are served like described in the documentation using the exported json file.

In the dev environment I would like to provide a read only API Token by default, which would allow me to activate the tolgee dev-mode and load all translations live from my tolgee instance. This would allow the usage of the dev app by everyone without needing access to the tolgee instance itself. Some people, for example translators, could install the chrome extension and should be able to override the API Token with a custom token with full access to tolgee, to change and adjust the translations if needed.

But this is not working, the extension does not allow to enter custom credentials when the app already is in tolgee dev-mode.

However when temporary switching to tolgee-prod mode, entering custom credentials in the chrome extension and then switching back to dev-mode, the custom credentials still get applied and I am able to edit the translations in place even if a different API token is already provided by the app.

This is pretty nice and it would be even better, if the extension would allow this by default and that it's always possible to enter custom credentials, no matter which mode is currently active in the running app.

Another thing I noticed:
The doc states, that the extension allows in place editing, when tolgee production-mode is active, but this does not work in my case. Maybe it's only the Angular version that makes problems here. I'm providing the UI package and only set the mode production.

Thanks again for the great project
Best regards

Morris

**Comment by stepan662** [comment]
Hey, Tolgee extension behavior is intentional as we tried to stick to either you are in development mode (and you use your .env) or in production mode (then you use extension). However your usecase make sense, so I'll allow to override https://github.com/tolgee/chrome-plugin/issues/9

The second thing is bug indeed. The "mode" somehow got quietly deprecated as it is automatically detected when "apiKey" is provided. It doesn't work correctly when you set it explicitly. I'll remove it from the config as it should be an internal state based on apiKey presence https://github.com/tolgee/tolgee-js/issues/2575. To avoid this issue just skip the mode property.

**Comment by stepan662** [comment]
It's released

**Comment by morrisjdev** [comment]
Awesome, thank you. I'll try it.
